// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: c4FCQiVEmUqfPef3MjSmg8
// Component: SDagfCRh-2CQ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import Button from "../../Button"; // plasmic-import: WoUXpKFRVp6X/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import { useScreenVariants as useScreenVariantsqExrow76Zrl } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: QExrow-76Zrl/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: c4FCQiVEmUqfPef3MjSmg8/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: SDagfCRh-2CQ/css

import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: YmZHPP8Bqtaf/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: wSb16lybm7DS/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: m3IaC3t3OSQT/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  landingPage?: Flex__<"div">;
  section?: Flex__<"section">;
  navigationBar?: Flex__<typeof NavigationBar>;
  hero?: Flex__<typeof PlasmicImg__>;
  heading?: Flex__<"div">;
  container?: Flex__<"div">;
  apriwa?: Flex__<"a"> & Partial<LinkProps>;
  asc?: Flex__<"a"> & Partial<LinkProps>;
  citadel?: Flex__<"a"> & Partial<LinkProps>;
  enginePlus?: Flex__<"a"> & Partial<LinkProps>;
  jvs?: Flex__<"a"> & Partial<LinkProps>;
  porsche?: Flex__<"a"> & Partial<LinkProps>;
  rizqyMotorsport?: Flex__<"a"> & Partial<LinkProps>;
  semenMerahPutih?: Flex__<"a"> & Partial<LinkProps>;
  siloMaritime?: Flex__<"a"> & Partial<LinkProps>;
  footer?: Flex__<"div">;
  logo?: Flex__<"div">;
  social?: Flex__<"div">;
  social2?: Flex__<"div">;
  social4?: Flex__<"div">;
  button?: Flex__<typeof Button>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    query: usePlasmicDataOp(() => {
      return {
        sourceId: "eA7ZA8G1r1sNAkLZ6fF4gN",
        opId: "dd53357a-e00e-4feb-963c-ea28429b31e8",
        userArgs: {},
        cacheKey: `plasmic.$.dd53357a-e00e-4feb-963c-ea28429b31e8.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsqExrow76Zrl()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"landingPage"}
          data-plasmic-override={overrides.landingPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.landingPage
          )}
        >
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <NavigationBar
              data-plasmic-name={"navigationBar"}
              data-plasmic-override={overrides.navigationBar}
              brand={
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__ugMcO
                  )}
                  component={Link}
                  href={`/`}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___5Sik0)}
                    displayHeight={"40px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: "/plasmic/blank_website_mobile_first/images/cncXPscIsvg.svg",
                      fullWidth: 449.49,
                      fullHeight: 98.63,
                      aspectRatio: 4.557335
                    }}
                  />
                </PlasmicLink__>
              }
              className={classNames("__wab_instance", sty.navigationBar)}
              closeButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__yh6Fr)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={"https://static1.plasmic.app/close.svg"}
                />
              }
              itemsGap={8}
              menuItems={
                <React.Fragment>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__yNWnR
                    )}
                    component={Link}
                    href={"/"}
                    platform={"nextjs"}
                  >
                    {"Home"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__h3JzT
                    )}
                    component={Link}
                    href={"/"}
                    platform={"nextjs"}
                  >
                    {"About"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__omr0V
                    )}
                    component={Link}
                    href={"/"}
                    platform={"nextjs"}
                  >
                    {"Contact"}
                  </PlasmicLink__>
                </React.Fragment>
              }
              openButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__i4GIy)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={"https://static1.plasmic.app/menu.svg"}
                />
              }
              responsiveBreakpoint={768}
            />

            <PlasmicImg__
              data-plasmic-name={"hero"}
              data-plasmic-override={overrides.hero}
              alt={""}
              className={classNames(sty.hero)}
              displayHeight={"320px"}
              displayMaxHeight={"none"}
              displayMaxWidth={
                hasVariant(globalVariants, "screen", "desktopOnly")
                  ? "800px"
                  : "100%"
              }
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={
                hasVariant(globalVariants, "screen", "desktopOnly")
                  ? "100%"
                  : "100%"
              }
              loading={"lazy"}
              src={{
                src: "/plasmic/blank_website_mobile_first/images/mainImagepng2.png",
                fullWidth: 6034,
                fullHeight: 4023,
                aspectRatio: undefined
              }}
            />

            <div
              data-plasmic-name={"heading"}
              data-plasmic-override={overrides.heading}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.heading
              )}
            >
              {"Collections"}
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(projectcss.all, sty.container)}
            >
              <PlasmicLink__
                data-plasmic-name={"apriwa"}
                data-plasmic-override={overrides.apriwa}
                className={classNames(projectcss.all, projectcss.a, sty.apriwa)}
                component={Link}
                href={`/${"apriwa"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___6Pbwl)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g74J
                    )}
                  >
                    {"Apriwa\nMotorsport"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ad4B5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ztio2
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__pzbGr)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__fJzD6)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"auto"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/apriwa2Xpng2.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"asc"}
                data-plasmic-override={overrides.asc}
                className={classNames(projectcss.all, projectcss.a, sty.asc)}
                component={Link}
                href={`/${"asc"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iRRoD)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xCnpo
                    )}
                  >
                    {"ASC Motorsport"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nlsgv)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8WXHq
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__uaRbc)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___5X3V4)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/asc2X2Xpng2.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"citadel"}
                data-plasmic-override={overrides.citadel}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.citadel
                )}
                component={Link}
                href={`/${"citadel"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__yaHgl)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lbdIp
                    )}
                  >
                    {"Citadel \nRacing Team"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__jQzzP)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ydcdg
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__jDDg)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__tLfKi)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"auto"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/citadel2Xpng.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"enginePlus"}
                data-plasmic-override={overrides.enginePlus}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.enginePlus
                )}
                component={Link}
                href={`/${"engineplus"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__o6HuT)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gxmbg
                    )}
                  >
                    {"Engine Plus \nMotorsport"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___564Ls)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xZgF
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__goR9K)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__bud4E)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/enginePlus2X2X2Xpng.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"jvs"}
                data-plasmic-override={overrides.jvs}
                className={classNames(projectcss.all, projectcss.a, sty.jvs)}
                component={Link}
                href={`/${"jvs"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__mi6Lc)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pMtFg
                    )}
                  >
                    {"JVS\nMotorsport"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__fWYwL)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1Jwcx
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__qzBo)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__prFrd)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"auto"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/jvs2X1Png.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"porsche"}
                data-plasmic-override={overrides.porsche}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.porsche
                )}
                component={Link}
                href={`/${"porsche"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__ynkes)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__waQOf
                    )}
                  >
                    {"Porsche\nMotorsport"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nmk3R)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7IuCi
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__lUuSf)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__jpCLs)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/baseBlue2Xpng.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"rizqyMotorsport"}
                data-plasmic-override={overrides.rizqyMotorsport}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.rizqyMotorsport
                )}
                component={Link}
                href={`/${"rizqy"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__hC2Bz)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__npVUo
                    )}
                  >
                    {"Rizqy \nMotorsport"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__zZld2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fa31T
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__i38E8)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__icsh)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"auto"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/rizqyMotorsport2Xpng.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"semenMerahPutih"}
                data-plasmic-override={overrides.semenMerahPutih}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.semenMerahPutih
                )}
                component={Link}
                href={`/${"smp"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___4OyYv)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kqgdo
                    )}
                  >
                    {"Semen Merah \nPutih "}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__sTzDv)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vfKqb
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__oxkNy)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__kv8Y2)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/semenMerahPutih2X2Xpng.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"siloMaritime"}
                data-plasmic-override={overrides.siloMaritime}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.siloMaritime
                )}
                component={Link}
                href={`/${"silo"}`}
                platform={"nextjs"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___8SuB)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lsnF
                    )}
                  >
                    {"Silo Maritime\nRacing Team"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__krpRa)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ollRf
                      )}
                    >
                      {"Shop Now"}
                    </div>
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__mPKvO)}
                      role={"img"}
                    />
                  </Stack__>
                </Stack__>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__fr51O)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"auto"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_website_mobile_first/images/btpn2X2Xpng.png",
                    fullWidth: 420,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
              <Stack__
                as={"div"}
                data-plasmic-name={"footer"}
                data-plasmic-override={overrides.footer}
                hasGap={true}
                className={classNames(projectcss.all, sty.footer)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"logo"}
                  data-plasmic-override={overrides.logo}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.logo)}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__dssr6
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__pGtHc)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"178px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/blank_website_mobile_first/images/cncXPsci1Invertedsvg.svg",
                        fullWidth: 178,
                        fullHeight: 40,
                        aspectRatio: 4.45
                      }}
                    />
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eGg8
                    )}
                  >
                    {"Official Apparels Partner"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"social"}
                  data-plasmic-override={overrides.social}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.social)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bEAxg
                    )}
                  >
                    {"Connect with Cars and Clo"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__kiaQh)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__egJhG
                      )}
                      component={Link}
                      href={"https://www.instagram.com/carsandclo/"}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___1Fhnw)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"32px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/blank_website_mobile_first/images/instagramsvg.svg",
                          fullWidth: 32,
                          fullHeight: 32,
                          aspectRatio: 1
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__ocLrT
                      )}
                      component={Link}
                      href={
                        "https://www.tiktok.com/@carsandclo?_t=8nQ5PnLKxmq&_r=1"
                      }
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__xYraU)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"32px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/blank_website_mobile_first/images/tiktoksvg.svg",
                          fullWidth: 32,
                          fullHeight: 32,
                          aspectRatio: 1
                        }}
                      />
                    </PlasmicLink__>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"social2"}
                  data-plasmic-override={overrides.social2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.social2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bPuBd
                    )}
                  >
                    {"Marketplace"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nsA0T)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__gtDi3
                      )}
                      component={Link}
                      href={"https://shopee.co.id/carsandcloofficial"}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__mpOg2)}
                        displayHeight={"32px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/blank_website_mobile_first/images/shopeesvg.svg",
                          fullWidth: 84,
                          fullHeight: 32,
                          aspectRatio: 2.625
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__fI9Rt
                      )}
                      component={Link}
                      href={"https://www.tokopedia.com/carsandcloofficial"}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__nmSqO)}
                        displayHeight={"32px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/blank_website_mobile_first/images/tokpedsvg.svg",
                          fullWidth: 99,
                          fullHeight: 32,
                          aspectRatio: 3.09375
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__qGjza)}
                      displayHeight={"32px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/blank_website_mobile_first/images/tShopsvg.svg",
                        fullWidth: 114,
                        fullHeight: 32,
                        aspectRatio: 3.5625
                      }}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___16749)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__vWnc4)}
                      displayHeight={"32px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/blank_website_mobile_first/images/bigcartesvg2.svg",
                        fullWidth: 89,
                        fullHeight: 32,
                        aspectRatio: 2.78125
                      }}
                    />
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"social4"}
                  data-plasmic-override={overrides.social4}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.social4)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qjixm
                    )}
                  >
                    {"Want to collaborate?"}
                  </div>
                  <Button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                    link={"mailto:cloandcars@gmail.com"}
                    shape={"sharp"}
                    showEndIcon={true}
                    target={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eFEjL
                      )}
                    >
                      {"Get in touch with us"}
                    </div>
                  </Button>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aU1Ez
                  )}
                >
                  {"\u00a9 2024 Cars and Clo"}
                </div>
              </Stack__>
            </Stack__>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  landingPage: [
    "landingPage",
    "section",
    "navigationBar",
    "hero",
    "heading",
    "container",
    "apriwa",
    "asc",
    "citadel",
    "enginePlus",
    "jvs",
    "porsche",
    "rizqyMotorsport",
    "semenMerahPutih",
    "siloMaritime",
    "footer",
    "logo",
    "social",
    "social2",
    "social4",
    "button"
  ],
  section: [
    "section",
    "navigationBar",
    "hero",
    "heading",
    "container",
    "apriwa",
    "asc",
    "citadel",
    "enginePlus",
    "jvs",
    "porsche",
    "rizqyMotorsport",
    "semenMerahPutih",
    "siloMaritime",
    "footer",
    "logo",
    "social",
    "social2",
    "social4",
    "button"
  ],
  navigationBar: ["navigationBar"],
  hero: ["hero"],
  heading: ["heading"],
  container: [
    "container",
    "apriwa",
    "asc",
    "citadel",
    "enginePlus",
    "jvs",
    "porsche",
    "rizqyMotorsport",
    "semenMerahPutih",
    "siloMaritime",
    "footer",
    "logo",
    "social",
    "social2",
    "social4",
    "button"
  ],
  apriwa: ["apriwa"],
  asc: ["asc"],
  citadel: ["citadel"],
  enginePlus: ["enginePlus"],
  jvs: ["jvs"],
  porsche: ["porsche"],
  rizqyMotorsport: ["rizqyMotorsport"],
  semenMerahPutih: ["semenMerahPutih"],
  siloMaritime: ["siloMaritime"],
  footer: ["footer", "logo", "social", "social2", "social4", "button"],
  logo: ["logo"],
  social: ["social"],
  social2: ["social2"],
  social4: ["social4", "button"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  landingPage: "div";
  section: "section";
  navigationBar: typeof NavigationBar;
  hero: typeof PlasmicImg__;
  heading: "div";
  container: "div";
  apriwa: "a";
  asc: "a";
  citadel: "a";
  enginePlus: "a";
  jvs: "a";
  porsche: "a";
  rizqyMotorsport: "a";
  semenMerahPutih: "a";
  siloMaritime: "a";
  footer: "div";
  logo: "div";
  social: "div";
  social2: "div";
  social4: "div";
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "landingPage") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("landingPage"),
  {
    // Helper components rendering sub-elements
    section: makeNodeComponent("section"),
    navigationBar: makeNodeComponent("navigationBar"),
    hero: makeNodeComponent("hero"),
    heading: makeNodeComponent("heading"),
    container: makeNodeComponent("container"),
    apriwa: makeNodeComponent("apriwa"),
    asc: makeNodeComponent("asc"),
    citadel: makeNodeComponent("citadel"),
    enginePlus: makeNodeComponent("enginePlus"),
    jvs: makeNodeComponent("jvs"),
    porsche: makeNodeComponent("porsche"),
    rizqyMotorsport: makeNodeComponent("rizqyMotorsport"),
    semenMerahPutih: makeNodeComponent("semenMerahPutih"),
    siloMaritime: makeNodeComponent("siloMaritime"),
    footer: makeNodeComponent("footer"),
    logo: makeNodeComponent("logo"),
    social: makeNodeComponent("social"),
    social2: makeNodeComponent("social2"),
    social4: makeNodeComponent("social4"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
