// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: c4FCQiVEmUqfPef3MjSmg8

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  embedCssProps?: Partial<
    Omit<React.ComponentProps<typeof EmbedCss>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, embedCssProps } = props;

  return (
    <EmbedCss
      {...embedCssProps}
      css={
        embedCssProps && "css" in embedCssProps
          ? embedCssProps.css!
          : "/* CSS snippet */\n\n@font-face {\n  font-family: 'DIN_Alternate_Bold';\n  src: url('https://cdcbjwnnxdsbwekkxdah.supabase.co/storage/v1/object/sign/Font/DIN_Alternate_Bold.ttf?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJGb250L0RJTl9BbHRlcm5hdGVfQm9sZC50dGYiLCJpYXQiOjE3MTkwNzc1NTIsImV4cCI6MTc1MDYxMzU1Mn0.IWZeSTSbTs6h_CTCBM8r1wZYXef0nw2F2q2tv0v6d6o&t=2024-06-22T17%3A32%3A32.327Z');\n}"
      }
    >
      {children}
    </EmbedCss>
  );
}
